### ISSUE TITLE
cant do update() to a model

### ISSUE THREAD

**Issue by Haizone** [GeneaLabs/laravel-model-caching#104]
whan i try to make for a model with chaching update i get that error:
Type error: Argument 2 passed to GeneaLabs\LaravelModelCaching\CacheTags::__construct() must be an instance of Illuminate\Database\Eloquent\Model, string given, called in

when i remove   use Cachable;

its work
how to fix that?

i use laravel 5.6

**Comment by mikebronner** [comment]
Thanks for reporting this. Can you please provide the eloquent query it is failing on?

**Comment by Haizone** [comment]
i just try to update info inside an exist model with caching and its give me that error

**Comment by mikebronner** [comment]
I understand. The information will help me replicate the problem.

**Comment by mikebronner** [comment]
@Haizone Please help me help you and provide the eloquent query you are running. I have a test that uses update, and its passing, so I need to see what you are doing different. Thank you!

**Comment by Haizone** [comment]
@mikebronner 
hi 
i have exist model with row in the db
i just try to change a filed in the model and use update() method to update in the db
and is didnt work i get that error:
"Type error: Argument 2 passed to GeneaLabs\LaravelModelCaching\CacheTags::__construct() must be an instance of Illuminate\Database\Eloquent\Model, string given, called in vendor\genealabs\laravel-model-caching\src\Traits\Caching.php on line 84"

id u whant u can give me your skype and i show u in live

**Comment by mikebronner** [comment]
@Haizone I need the code that contains the 1st->update().

**Comment by Haizone** [comment]
@mikebronner

`$product= Product::get();
    $newmodel = str_replace(strtolower($product->manufacturer->english_name), "", strtolower($product->model));

    if((count(preg_split('/\s+/', $newmodel))) >= 3){
      $product->old_model = $product->model;
      $product->model = $newmodel;
      $product->update();
    }
`

**Comment by mikebronner** [comment]
Hi @Haizone, thanks, that is the information I needed.

I would like to make one recommendation: the usage of `update()` in your code is not recommended. `->update()` should be used with QueryBuilder chains, like described in the documentation here (https://laravel.com/docs/5.6/eloquent#updates), but not for model updates. instead simply use `->save()`.

**Comment by mikebronner** [comment]
I tried to replicate your issue, but was unable to. Can you also provide the last full stack trace from `/storage/logs/laravel.log`. I don't think the update query is causing the problem. The stack trace will tell us exactly what line in your code is causing the error. From there we will be able to see if there is a problem with the package.

**Comment by mikebronner** [comment]
The problem appears to be with your model. Are you using this on an Eloquent model? It is trying to create cache tags from an object called "Mi A1 64GB", which is interpreted as a String, and not as a model. From what I can see this is not an issue with this package. I would recommend following the stack trace and debugging your code step by step to see what is going on. If you can provide further evidence that this is a problem with this package, please re-open this issue and add the information. Sorry for the bad news, but good luck! (Unfortunately I am unable to help people one-on-one debugging their projects due to time-constraints. If you would like to hire me to implement the package, I am available to do so here: https://genealabs.17hats.com/p#/lcf/hrspbdcvncvnbdpkngrcrxnrwsbghcws)
