### ISSUE TITLE
Caching Performance Is Slow

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#134]
@howya wrote:

> Hi Mike,
> 
> I've put together a very simple example at:
> 
> https://github.com/howya/laravel_builder_cache
> 
> Just clone it, composer install, then setup the phpunit.xml environment variables to point at your MySQL server and Redis server.
> 
> Once setup you can run 'composer test' to run a simple performance test. The performance test runs a 1000 iteration loop of query calls (I chose these queries as they are similar to what I require in a project I'm working on). The loop is replicated 3 times:
> 
> - Once for queries against Non-Cached 'standard' models
> - Once for queries against Builder-Cached models - this is an experimental cache that I'm playing with
> - Once for queries against Model-Cached models - this is your package
> 
> The test is trivial and does not reflect real world usage as it does not bust the cache and the query domain space is very small i.e. MySql is probably hitting its own cache 100% of the time.
> 
> The results I get are:
> 
> "Non-Cached time taken: 25.299576044083"
> "Builder-Cached time taken: 24.184181928635"
> "Model-Cached time taken: 35.246420145035"
> 
> I would have assumed that our caching strategies would have been the same or slightly slower than 'Non-Cached' in this test as MySql is probably hitting its own cache 100% of the time. I'm not sure why yours is approx 50% slower. Have I made an error when implementing your caching package?

**Comment by mikebronner** [comment]
@howya Off the top of my head, this package is more suited to cache complex queries that take a long time to run on their own. That's where the performance improvement lies.

Thanks for putting together a repo, I will play with it and see what's happening. I know that properly configuring redis or memcached can have a large effect on performance.

**Comment by howya** [comment]
Hi Mike,

Your explanation re use-case makes sense. The strategy I'm working on is designed for slowly changing data such as application meta / config data etc. As such it is designed to make as few cache calls per query as possible (it stores the whole SQL result in a single key). I think this is the main difference in performance as I notice your package makes many more cache calls than my strategy, as such it will become more susceptible to latency etc.

I made a few updates to the test repo (to compress 'builder-cached' cache entires - big positive impact on performance) and also adjusting the total intersection records in the test data set. This has the effect of changing the size of the record set returned and makes it a more real world scenario:

(redis-cli flushall called before each test)

With 600 intersection records:
"Non-Cached time taken: 79.835070848465"
"Builder-Cached time taken: 69.807591199875"
"Model-Cached time taken: 127.18196392059"

I then tested with 300 intersection records:
"Non-Cached time taken: 54.8621301651"
"Builder-Cached time taken: 44.611806154251"
"Model-Cached time taken: 82.691457986832"

I then tested with 60 intersection records:
"Non-Cached time taken: 30.076621055603"
"Builder-Cached time taken: 26.164316177368"
"Model-Cached time taken: 39.56648182869"

I then tested with 9 intersection records:
"Non-Cached time taken: 24.722324848175"
"Builder-Cached time taken: 22.5115878582"
"Model-Cached time taken: 30.38514995575"

To Note: I'm using a simple Redis server within a Docker container on my Mac, average Redis latency is 0.42 - The test results above would seem to indicate that less cache calls with each call returning a larger data set is more performant than more cache calls with each call returning a very small data set. I'm guessing that this could change considerably if the Redis server were optimised for latency rather than throughput.

Perhaps an adaptive approach to deciding if you should store many small cache items or fewer large cache items would give you the best of both worlds?

**Comment by mikebronner** [comment]
You've got me curious: would you mind running these tests against memcached and post the results?

**Comment by howya** [comment]
Certainly, I'll take a look tomorrow. Would be great if you could have a quick look at the repo as I'm not 100% sure I've implemented your package correctly.

**Comment by mikebronner** [comment]
I probably wont have time today, will most likely have to wait until the weekend. I'll let you know if I do. :) Thanks!

**Comment by howya** [comment]
Hi Mike,

I've re-run the tests against Memcached and Redis - I repeated the Redis test runs as I had to use a slightly different docker environment for Memcached, so wanted all things to be equal between Redis and Memcached results. You'll see that the re-run tests for Redis are better than yesterdays results, I think this is down to PHP to Redis having a lower latency as they now exist in their own containers, rather than PHP executing directly on my laptop (as reflected in yesterday's results).

In my latest environment I have a separate container for MySQL, PHP, Redis and Memchached servers. I run the PHP tests from within the PHP container, rather than directly  I have not attempted to optimise Redis or Memcached. After each run the Memcache / Redis cache is flushed. 

Results attached.

[Workbook1.xlsx](https://github.com/GeneaLabs/laravel-model-caching/files/2062256/Workbook1.xlsx)

Regards,

Rob

**Comment by howya** [comment]
If I understand you correctly then the query count will be the same for each test. Each test has 1000 iterations and each iteration has the following 8 queries:

`
        $class::with('integrated')->findOrFail(1)->integrated;
        $class::findOrFail(2);
        $class::with('integrated')->get();
        $class::whereHas('integrated', function ($query) {
            $query->where('client_id', '=', '2');
        })->get();
        $class::with('integrated')->findOrFail(2)->integrated;
        $class::findOrFail(3);
        $class::with('integrated')->get();
        $class::whereHas('integrated', function ($query) {
            $query->where('client_id', '=', '1');
        })->get();
`
That makes a total of 8000 Model queries per test (I used the above queries as they are similar to the queries I'm using in a current project).

So what changes between each test? It's the number of records in the intersection, which correlates to the size of the result set i.e. 600 interaction records could result in a result set of 200 rows (the parent / child id's in the intersection will be equally split between 1, 2 or 3 and the parents / children are id'd as 1,2 or 3 etc). 

The test is designed to assess performance of caching result sets and I wanted to understand impact of size of result set on performance - particularly the impact of storing the result set against many cache entries (your method) or storing the result set in one compressed cache entry (my method). Potentially, with large result sets, there may be no point in caching, it may simply be faster to go back to the DB.....

Have I understood your question correctly?

**Comment by howya** [comment]
Just to add a quick update. I've done some analysis on Redis to understand number of keys used and volume of key requests. I'd made some assumptions about your implementation which are clearly wrong - I thought your volume of cache requests would grow with the result set size, but they are relative to the number of queries. 

For 1000 x 8 Model queries your package uses 19 keys and makes approximately 44k cache requests.
For the same my implementation uses 15 keys and makes approximately 28k cache requests.

Is there a bug creating surplus cache requests because it looks like that is where you're losing performance?

Hope this helps.

**Comment by mikebronner** [comment]
Regarding queries I am referring to the number of times the database is hit. There should only be one (or a few) initial queries the first time around, and then for subsequent requests all should come from the cache.

The cache key request count is good info, that will help me when I look at it. I don't have an answer at the top of my head.

**Comment by mikebronner** [comment]
here is my time results when running against 10 iterations:
```
"Non-Cached time taken: 2.6008288860321"
"Builder-Cached time taken: 2.8003520965576"
"Model-Cached time taken: 1.0957701206207"
```

**Comment by howya** [comment]
Hi Mike, did you clear your Redis cache before each test? As I mentioned, I've just set up Redis / Memcached on a local docker container without any attempt at optimisation. I'll take another look this week.

**Comment by mikebronner** [comment]
I ran your code exactly as you had it, all i changed was the configuration.

**Comment by howya** [comment]
Hi Mike,

I've updated the repo as follows:

- It now clears the cache before test (I was doing this manually)
- I've set it to a SQLite DB

When I run the test it now shows the following results for 600 intersection records:

"Non-Cached time taken: 14.588853120804"
"Builder-Cached time taken: 23.193886041641"
"Model-Cached time taken: 33.07765007019"
 
I'd expect SQLite to be faster than caching.

The only difference that there could be is with the Redis environment. Can you pull this repo and only change the following in phpunit.xml to ensure that you're not introducing other issues?

       <env name="REDIS_HOST" value="redis"/>
        <env name="REDIS_PASSWORD" value="yourpassword"/>
        <env name="REDIS_PORT" value="6379"/>
        <env name="MODEL_CACHE_STORE" value="redis"/>

Regards,

Rob

**Comment by mikebronner** [comment]
Here are the results:

```
"redis"
array:5 [
  "driver" => "memcached"
  "persistent_id" => null
  "sasl" => array:2 [
    0 => null
    1 => null
  ]
  "options" => []
  "servers" => array:1 [
    0 => array:3 [
      "host" => "127.0.0.1"
      "port" => 11211
      "weight" => 100
    ]
  ]
]
"Non-Cached time taken: 88.467418909073"
"Builder-Cached time taken: 95.473206043243"
"Model-Cached time taken: 39.337776899338"
```

And here is my config file:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>

        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_KEY" value="base64:nuiNs2u8nhcU/c00PGLqS7qKUl7b1GuydISIxaALZrU="/>
        <env name="APP_ENV" value="testing"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="MAIL_DRIVER" value="array"/>

        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>

        <env name="REDIS_HOST" value="192.168.10.10"/>
        <env name="REDIS_PASSWORD" value="NULL"/>
        <env name="REDIS_PORT" value="6379"/>
        <env name="MODEL_CACHE_STORE" value="redis"/>
    </php>
</phpunit>
```

**Comment by howya** [comment]
Tried it with your phpunit.xml with just REDIS_HOST and REDIS_PASSWORD updated and get the following:

"Non-Cached time taken: 16.817641973495"
"Builder-Cached time taken: 26.729877948761"
"Model-Cached time taken: 33.037648200989"

I've no idea why we get such a discrepancy, I can only imagine it's my very basic Redis install - though why this causes your code to perform poorly (and not mine) I have no idea.

I'll see if I can replicate this in work with an optimised Redis environment.

**Comment by mikebronner** [comment]
Try using a Homestead environment to test. I bet containers are hurting performance if they are optimized. I use Homestead because it mirrors my Laravel Forge servers closely.

**Comment by mikebronner** [comment]
@howya I'm going to close this for now, as this is really an environmental issue, and not necessarily a problem with this package. Please do update with your findings if you are able to. Thanks!
