### ISSUE TITLE
Where does the cache store?

### ISSUE THREAD

**Issue by PhanPirang** [GeneaLabs/laravel-model-caching#153]
I just follow your video tutorial.

My model doesn't have any relationship.

Do I need to change cache_driver to redis in .env file?
In case I don't change it. It'll create cache as files.

When I change cache_driver to redis, the cache is stored, but it automatically remove from Redis after several seconds.

**Comment by mikebronner** [comment]
Hi @PhanPirang , yes redis or memcached are the preferred methods. Using file or array will result in degraded performance. If your redis cache is being cleared every few minutes, you will need to look into providing it more space, memory, or otherwise optimize its performance in relation to your data requirements. Unfortunately that's not something I am able to help with.

Also, keep in mind that the cache is cleared when updating, creating, or deleting related items as well, if you are loading relationships. That might be what you are seeing.
