### ISSUE TITLE
Relationships doesn't invalidate the cache

### ISSUE THREAD

**Issue by JapSeyz** [GeneaLabs/laravel-model-caching#157]
**Describe the bug**
When using Laravel Nova to attach a model to a hasMany relationship, it doesn't invalidate the cache, and the new model doesn't show up until it's manually cleared.

**Eloquent Query**
Please provide the complete eloquent query that caused the bug, for example:
```php
$model->setRelation(
    $model->{$request->viaRelationship}()->getPivotAccessor(),
    $pivot = $this->findPivot($request, $model)
);
[$pivot, $callbacks] = $resource::fillPivot($request, $model, $pivot);

$pivot->save();
```
I believe this may be due to the fact that it doesn't really touch the parent tables, as the actual query looks like this:

```sql
insert into `complimentary_products` (`coupon_id`, `product_id`) values ('1', '3')
```

where it then should invalidate the cache for coupon 1 or atleasts it's products, and for product 3 or atleast for it's coupons.

Any thoughts on this?

PHP Version | 7.2.4
Laravel Version | 5.6.34
Nova Version | 1.0.5

**Comment by JapSeyz** [comment]
Duplicate of #127 albeit not lazyloading

**Comment by JapSeyz** [comment]
Reopening as it doesn't seem to be related afterall. I think it may be because it's being inserted through the eloquent relationship, and therefore it doesn't fire the `static::pivotAttached` that is being listener for in the `ModelCaching`.

I'll look for ways to solve this.

**Comment by JapSeyz** [comment]
It's possible to overpower this, if you set the $touches array on the pivot Model, but it's not optimal

**Comment by JapSeyz** [comment]
The best way i found was to add disableCache() to the relationship declaration...

I'll investigate whether it happens with other relationships too.

PS. this has nothing to do with Laravel Nova. I tested it with Tinker too, and same thing happened, the cache wasn't invalidated/

**Comment by mikebronner** [comment]
@JapSeyz Thanks, I will look into this as soon as I get some time. :)

**Comment by mikebronner** [comment]
@JapSeyz I believe this is because setRelation does not persist the relationship data, and I don't think it is meant to. Rather, it is a method to override associated objects during run-time.

I would look into another way of persisting your relationships other than using setRelation. At this time this is not something that I believe needs to be addressed in this library.

However, `$pivot->save()` should trigger this clearing of the cache. Can you provide more information about what your $pivot object is? If it's a model it will need to use Cachable as well. It is good practice to use explicit models instead of inserting things via pivot methods on relationships. If a pivot table holds more than just the relationship IDs, then it should act as a full model. This principle has saved me a ton of work and worry over the years.

I'm closing this for now. Feel free to reopen with additional information.
