### ISSUE TITLE
Cache Not Working Along with Observer

### ISSUE THREAD

**Issue by RobinHoo1973** [GeneaLabs/laravel-model-caching#171]
**Describe the bug**
As the Model Article content field is stored the rich text with base64 encoded string, and an observer was created for encoding & decoding while saving and reading. It works fine until the trait mode Cachable involved in the Article model. And when it removed from the model, everything returned ok.

**Eloquent Query**
Please provide the complete eloquent query that caused the bug, for example:
**Observer**
_/app/Observers/ArticleObserver.php_
```php
<?php

namespace App\Observers;
use App\Article;

class ArticleObserver
{
	public function saving(Article $article)
	{
		$article->content = bin2hex($article->content);
	}

	public function retrieved(Article $article)
	{
		// if(strlen($article->content)%2==1 || preg_replace('/[a-zA-Z0-9]+/','',$article->content)!='')
		// return;
		try{
			$article->content = hex2bin(trim($article->content));
		}
		catch (\Exception $e) {
			return;
		} 
	}
}
```
_/app/Providers/ArticleModelServiceProvider.php_
```php
<?php

namespace App\Providers;
use Illuminate\Support\ServiceProvider;

class ArticleModelServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        \App\Article::observe(\App\Observers\ArticleObserver::class);
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```
**Stack Trace**
The full stack trace from your log file.

**Environment**
 - PHP: [e.g. 7.1.0]
 - OS: [e.g. Ubuntu 18.04]
 - Laravel: [e.g. 5.6.15]
 - Model Caching: [e.g. 0.2.61]

**Additional context**

**Comment by mikebronner** [comment]
Hi @RobinHoo1973, I'm out of the country at the moment, I will take a look. In the mean while, can you paste the code for your observer here as well? Thanks!

**Comment by RobinHoo1973** [comment]
> Hi @RobinHoo1973, I'm out of the country at the moment, I will take a look. In the mean while, can you paste the code for your observer here as well? Thanks!

Yes, I just updated my issue report with the observer code included. Thanks for your prompt response.

**Comment by mikebronner** [comment]
Thanks! I will have to create a test for observers. Give me a few weeks. If you would like to take a stab at submitting a PR with a new unit test or even an update to the functionality, that would be great! :)

**Comment by RobinHoo1973** [comment]
> Thanks! I will have to create a test for observers. Give me a few weeks. If you would like to take a stab at submitting a PR with a new unit test or even an update to the functionality, that would be great! :)

Take your time and enjoy your trip, it's not urgent case. :)

**Comment by mikebronner** [comment]
@RobinHoo1973 I created a test for observers and do not see an issue with using observers. It works as expected. Please provide the complete query that you are running.

**Comment by mikebronner** [comment]
I'm closing this for now due to inactivity. Please feel free to reopen with additional information if you still have this issue.

**Comment by paularmstrong80** [comment]
Hi Mike,

First, thank you for the great package, really appreciate your work!

I came across this issue when attempting to hook into the model's retrieved event.

The retrieved event only fires if the result hasn't been cached. Once the result is in cache, it no longer fires.

To work around the issue I had to do the following:

1. Replaced newEloquentBuilder in base model to return extended **GeneaLabs\LaravelModelCaching\CachedBuilder** if model is cachable.

`
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use GeneaLabs\LaravelModelCaching\Traits\Cachable;
use App\Database\Eloquent\Builder\OverrideCachedBuilder;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;

abstract class BaseModel extends Model
{
    use Cachable;

    public function newEloquentBuilder($query)
    {
        if (! $this->isCachable()) {
            $this->isCachable = false;

            return new EloquentBuilder($query);
        }

        return new OverrideCachedBuilder($query); // call custom extended CachedBuilder
    }

}
`

2. Override CachedBuilder cachedValue method with a modified version that fires the retrieved model event.

`
namespace App\Database\Eloquent\Builder;

use GeneaLabs\LaravelModelCaching\CachedBuilder;

class OverrideCachedBuilder extends CachedBuilder
{
    public function cachedValue(array $arguments, string $cacheKey)
    {
        $method = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 2)[1]['function'];
        $cacheTags = $this->makeCacheTags();
        $hashedCacheKey = sha1($cacheKey);
        $result = $this->retrieveCachedValue(
            $arguments,
            $cacheKey,
            $cacheTags,
            $hashedCacheKey,
            $method
        );

        // start - my hack to fire model retrieved event
        if ($resultValue = data_get($result, 'value')) {
            try {
                if (is_subclass_of($resultValue, 'Illuminate\Database\Eloquent\Model')) {
                    $resultValue->fireModelEvent('retrieved', false);
                }
            } catch (\Throwable $th) {
                //throw $th;
            }
        }
        // end - my hack to fire model retrieved event

        return $this->preventHashCollision(
            $result,
            $arguments,
            $cacheKey,
            $cacheTags,
            $hashedCacheKey,
            $method
        );
    }
}
`

My solution is not pretty, but works. I had troubles doing it other ways because of the debug_backtrace in the cacheValue event.

If there's a way to improve this solution, and/or get it into core, that would be amazing.

Kind Regards,
Paul
