### ISSUE TITLE
Caching custom attributes

### ISSUE THREAD

**Issue by webard** [GeneaLabs/laravel-model-caching#220]
When Model has a custom attributes like
```
public function getCanBuyAttribute()
{
        return SOME_HARD_WORK_CALCULATING_CAN_I_BUY_SOMETHING;
}
```

that attributes are not stored in cache. It is problem when some hard calculations are present in custom attributes methods.

**Comment by mikebronner** [comment]
This is expected behavior. Only eloquent queries are cached. You would have to return the result of eloquent queries from within the custom attribute for them to be cached. Sorry, this functionality probably won't ever be part of this package, as this package is meant to cache eloquent queries, and not model instances.
