### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by cyberfly** [GeneaLabs/laravel-model-caching#252]
Hi I currently on Laravel 5.7 and package version 0.4.0 and encounter this error on certain eloquent where condition. 

I found your comment that this was fixed on version 0.4.12 however nothing to update when try to update the package

`composer update genealabs/laravel-model-caching`

https://github.com/GeneaLabs/laravel-model-caching/issues/227#issuecomment-479624508

How to fix it? Thanks

![image](https://user-images.githubusercontent.com/1756170/58075499-735be500-7bda-11e9-9364-beb1baaa98af.png)

**Comment by mikebronner** [comment]
Hi @cyberfly, unfortunately you have to upgrade to Laravel 5.8. While the package is in pre-release, i don't support historical versions of Laravel. Sorry for the inconvenience.

**Comment by cyberfly** [comment]
@mikebronner Thanks, any best practice that I can follow to apply the fixed manually as updating Laravel version is not an option right now and your package kind of too good not to be use

**Comment by mikebronner** [comment]
You can fork this package and try to force compatibility in `composer.json` by setting the appropriate Laravel versions. After that you could run PHPUnit to make sure all tests pass and fix the code for any failing tests in your fork. Once you get PHPUnit to pass, you can install your fork into your project by forcing your project's `composer.json` to look at your fork instead of this repo to install the package (look into Composer's `repositories` options). I hope that helps! Good luck :)
