### ISSUE TITLE
Implement PHPREDIS instead of PREDIS.

### ISSUE THREAD

**Issue by wilbur-oo** [GeneaLabs/laravel-model-caching#344]
predis was last updated in 2017, and laravel has also recommended phpredis, I personally think it should be replaced by phpredis

**Comment by mikebronner** [comment]
@wilbur-oo Thanks for the recommendation! :) I'll work on getting that updated. :)

**Comment by mikebronner** [comment]
The concern I have is with the configuration changes needed to make Phrpredis work with Laravel, while PREDIS works out of the box with no changes. That being said, PREDIS is struggling from a maintenance point of view.
On the other hand, PHPREDIS requires the PECL extension to be installed, which may or may not be easy to do. Further, it's not installed in Homestead or on forge servers by default. For that reason I'm holding off for now until this becomes easier to manage in the future.

**Comment by wilbur-oo** [comment]
Yes, I agree with your concerns.
But for me personally, the laravel-model-caching package is to improve production performance, so in order to achieve high performance, installing an extension should not be a big problem.
Of course, this is just my personal opinion. I respect your ideas. After all, the change of an extension package ’s dependencies will affect too many users.
Or I think it is possible to adapt two methods, that is, the willingness to use predis or phpredis is up to the user to decide.

**Comment by mikebronner** [comment]
Good points! Is there something in the package that is preventing you from using PHPREDIS? Since it's all on the configuration end, and this package doesn't configure the REDIS provider for you, you should be able to.

Would love to hear the steps you need to take to get PHPREDIS to work with the package, and if it throws any errors.

**Comment by wolfpack4417** [comment]
I'm also having an issue getting PHP Redis working with this package. I decided on that instead of predis because of the warning in this section of the docs: https://laravel.com/docs/7.x/redis#introduction

I had used Predis before but if support is going to be removed from Laravel potentially I didn't want to waste time using it. Is that the only option for this library though? If so I might go back and use Predis until this package works with PHP Redis as well.

**Comment by mikebronner** [comment]
@wolfpack4417 Could you provide the stack trace of the errors you are getting?

**Comment by wolfpack4417** [comment]
Sorry I think this was on my end although I haven't figured it out yet. I think it has something to do with PHP Redis not being enabled on my docker container. I'm getting '1' when I run `extension_loaded('redis')` in the browser but not when I run `php artisan modelCache:clear`. I'll post back if I discover it wasn't an issue with my PHP Redis installation.

**Comment by mikebronner** [comment]
Thanks, that would be great! Ideally this package should be decoupled from your choice of caching driver. :)

**Comment by mikebronner** [comment]
Sorry for the delay on this. Please try release 0.10.0 and let me know how it works.

**Comment by mikebronner** [comment]
This is now easy, as Laravel Forge servers ship with PHPRedis already installed.
