### ISSUE TITLE
Add support for Laravel 10

### ISSUE THREAD

**Issue by faytekin** [GeneaLabs/laravel-model-caching#439]
Add support for Laravel 10, which is [expected to be released at February 7th, 2023](https://laravel.com/docs/master/releases#support-policy).

A starting point could be to look at the upgrade to Laravel 9 (https://github.com/GeneaLabs/laravel-model-caching/pull/420).

**Comment by mikebronner** [comment]
Happy to accept a PR for this, will get to it as soon as I can otherwise. :)

**Comment by daika7ana** [comment]
The [Database Expressions](https://laravel.com/docs/master/upgrade#database-expressions) change seems to be the only breaking one that I've managed to find.

The fix for this I managed to implement was [this](https://github.com/daika7ana/laravel-model-caching/commit/3397031c5b3d80cd2a168173f9779e626da27158?diff=split#diff-24a84b1fd190ebb1de9ff7bebef697d34dc0f1bb2ddd97f57c3e61b17fcbdf3bR202-R223) with all tests passing except for Laravel Nova tests which I had to skip as I don't own it.
