### ISSUE TITLE
Artisan Command To Clear Specific Model Cache

### ISSUE THREAD

**Issue by Nowi5** [GeneaLabs/laravel-model-caching#45]
# Question
1. Would that reduce the amount of select queries to the db?
Example issue just because of translations:
![laravel_queries](https://user-images.githubusercontent.com/27913135/34456888-17e694f8-eda2-11e7-903b-ba90c5c1d68d.JPG)

2. Shouldn't that be part of Laravel standard?
3. How can I integrate these in Vendor Models e.g. https://github.com/barryvdh/laravel-translation-manager/issues/227 ?
4. How can I delete the cache e.g. when a change was made direct on the database?

## Environment
Laravel Version: 5.5
PHP Version: 7

Thank you and a happy new year.

**Comment by mikebronner** [comment]
1. I believe this would be a good use-case for that.
2. I believe it was in Laravel 4, but was removed in Laravel due to complexities.
3. That is hard to do. I don't have a viable solution for you at this time for models that you don't control yourself.
4. You would have to flush the cache after making manual database changes: `php artisan cache:clear`.

Hope this helps answer some of your questions. :) Happy new year! Please feel free to re-open to continue the conversation if you have more questions.

**Comment by Nowi5** [comment]
Thank you for the very quick answer. I have one additional question regarding 4.:

Is there a possibility to delete only the model cache or even more specific to delete the only one specific model cache? Would love to have a separate artisan command.
The reason is, that I don't like to clear all caches although I have just made on entry in one model out of 30.

Thanks.

**Comment by mikebronner** [comment]
That's actually a great idea: have a command to clear all caches for a given model. The complexity is dealing with relationships. Let me see what I can do :). Thanks for bringing this up.

**Comment by mikebronner** [comment]
@Nowi5 Can you give 0.2.14 release a shot and see if this does what you need? (I'll be releasing it momentarily, just updating readme and change-logs.
