### ISSUE TITLE
When cache invalidation happens ?

### ISSUE THREAD

**Issue by gustavobgama** [GeneaLabs/laravel-model-caching#98]
# Issue
My issue is really a clarification about how this library works. I created a fresh installation of laravel and added the model caching package.

I've created a simple model using the cachable trait:

```
class Order extends Model
{
    use Cachable;
}
```

After, using the tinker and a factory I've created 10 orders and listed them using **App\Order::all()**. This returns to me the 10 orders from the cache. Nice !

After that I removed one of the orders with **App\Order::destroy(10)** and the result of **App\Order::all()** continued to be the 10 orders.

Is this the expected behavior ? Is there a way to invalidate cache not using the command **php artisan modelCache:flush --model=\\\App\\\Order** but in every database change ?

By the way, I'm used the sqlite for this test.

Thanks in advance !!

## Environment
Laravel Version: *5.6.7*
Laravel Model Caching Package Version: *0.2.47*
PHP Version: *7.1.8*
Operating System & Version: *Ubuntu 17.10*

**Comment by mikebronner** [comment]
Thanks for this report! I will check to make sure destroy is working as expected. I may only be invalidating on `delete()`. 👀

**Comment by gustavobgama** [comment]
Thanks for the fast reply !

I think may be it can be an issue with the **App\Order::all()** method.

I made the following test:

```
$order = App\Order::find(1);
$order->customer = 'modified customer';
$order->save();
```
And I can see the `modified customer` retrieving order from cache using methods like **App\Order::find(1)** and **App\Order::first()**, but still can't see the `modified customer` using the **App\Order::all()** method.

I hope these additional infos help :smile:

**Comment by mikebronner** [comment]
I am able to replicate the issue ... working on identifying the solution. :|

**Comment by mikebronner** [comment]
@gustavobgama Thanks for reporting all the details on this bug! That helped me identify the issue and fix it in version 0.2.50. I spent all afternoon debugging, but finally found that the problem was not in the way invalidation worked, but that the `all()` method was not using the correct tags, so was causing invalidation issues, that others have been reporting, but I have not been able to replicate so far with the information I had been given. Your use-cases led me to that fix, as well, of course, to adding the missing cache invalidation for `destroy()`. Thanks again!

Please let me know how this works for you.

**Comment by gustavobgama** [comment]
@mikebronner Great !!

Thanks for the hard work to fix and the explanation ! I'm going to get the new release !

I'm glad to help

**Comment by denitsa-cm** [comment]
I am encountering something similar. 

When creating a new model with `Model::create()`, the call to `all()` doesn't return the newly created model.
