### ISSUE TITLE
Cache Keys does not recognize different databases

### ISSUE THREAD

**Issue by dtvmedia** [GeneaLabs/laravel-model-caching#99]
If you have multiple databases with tables which have the same names, then you get collisions due to the key not recognizing the database name. That should be supported imo. Otherwise this cannot be used for example in tenant systems.

**Comment by mikebronner** [comment]
Excellent idea @dtvmedia! There this package does have the concept of adding prefixes, but automatically adding the connection would be good. I will add this functionality later today!

**Comment by mikebronner** [comment]
This should now be available in release 0.2.48. Please let me know how it works for you! :)

**Comment by bastian-schur** [comment]
Hey,

its possibile to change the connection detection to database name instead of connection name? We use a tenant system that has a connection named "tenant" but the database is changed on a middleware for every tenant.

I think this has no effects to the feature for users who work not with this manipulation!
